#!/usr/bin/env bash
# Node-level tuning for a small Odoo node. Idempotent; run by install.sh (first install
# and after every redeploy) and safe to run again at any time.
#   - OOM priorities: under memory pressure the kernel kills IDE servers and other
#     processes first, Odoo next, nginx and PostgreSQL last.
#   - Stops remote IDE servers left running after the editor disconnected (ide-reaper.sh).
#   - Caps the systemd journal and switches off jobs of the OS image an Odoo node does
#     not need (file indexing, man pages, MOTD news, local mail daemons that are unused).

. "$(dirname "$(readlink -f "$0")")/common.sh"

# --- OOM priorities (-1000 = never, 1000 = first) --------------------------------
oom_dropin() {
  local unit=$1 score=$2
  mkdir -p "/etc/systemd/system/$unit.d"
  printf '# Generated by %s\n[Service]\nOOMScoreAdjust=%s\n' "$JPS_DIR/optimize-node.sh" "$score" \
    > "/etc/systemd/system/$unit.d/20-jps-oom.conf"
}
# The drop-ins apply from the next start; also set them on what runs now (main process
# and children inherit it only when they are forked).
oom_running() {
  local unit=$1 score=$2 pid
  pid=$(systemctl show -p MainPID --value "$unit" 2> /dev/null || echo 0)
  [ "${pid:-0}" -gt 0 ] || return 0
  for p in $pid $(pgrep -P "$pid" || true) $(for c in $(pgrep -P "$pid" || true); do pgrep -P "$c" || true; done); do
    echo "$score" > "/proc/$p/oom_score_adj" 2> /dev/null || true
  done
}
oom_dropin postgresql@.service -900
oom_dropin nginx.service -600
oom_dropin odoo.service -300
load_state
oom_running "postgresql@${PG_MAJOR:-0}-main.service" -900
oom_running nginx.service -600
oom_running odoo.service -300

# --- Idle IDE servers ----------------------------------------------------------------
cat > /etc/systemd/system/odoo-ide-reaper.service << EOF
[Unit]
Description=Stop remote IDE servers left running without an SSH session

[Service]
Type=oneshot
ExecStart=${JPS_DIR}/ide-reaper.sh
EOF
cat > /etc/systemd/system/odoo-ide-reaper.timer << 'EOF'
[Unit]
Description=Check for idle remote IDE servers every 5 minutes

[Timer]
OnBootSec=5min
OnUnitActiveSec=5min

[Install]
WantedBy=timers.target
EOF

# --- Journal: at most 100 MB on disk -----------------------------------------------
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/20-jps.conf << 'EOF'
# Generated by /opt/odoo/jps/optimize-node.sh
[Journal]
SystemMaxUse=100M
RuntimeMaxUse=50M
EOF

# --- Jobs of the OS image an Odoo node does not need ----------------------------------
# plocate indexes the whole disk every day (filestore included): pure I/O for nothing.
for unit in plocate-updatedb.timer man-db.timer motd-news.timer exim4-base.timer; do
  systemctl disable --now --quiet "$unit" 2> /dev/null || true
done
# Odoo sends mail through its own SMTP settings; the image's local mail daemons are
# unused (exim4 does not even start on this template).
for unit in exim4.service postfix-mta-sts-resolver.service; do
  systemctl disable --now --quiet "$unit" 2> /dev/null || true
done

systemctl daemon-reload
systemctl restart systemd-journald 2> /dev/null || true
systemctl enable --now --quiet odoo-ide-reaper.timer
log "Node tuning applied (OOM priorities, idle IDE reaper, journal cap, unused jobs off)"
