#!/usr/bin/env bash
# Writes the Postgres settings for this node's size and the access rules.
# Usage: tune-postgres.sh [--restart]
# Called by install.sh, upgrade-postgres.sh and after vertical scaling (onAfterSetCloudletCount).

. "$(dirname "$(readlink -f "$0")")/common.sh"
load_state
[ -n "${PG_MAJOR:-}" ] || die "no PG_MAJOR in $STATE_FILE"

restart=0
[ "${1:-}" = --restart ] && restart=1

conf_dir=/etc/postgresql/$PG_MAJOR/main
[ -d "$conf_dir" ] || die "cluster $PG_MAJOR/main not found"

mem=$(mem_mb)
shared_buffers=$(clamp $((mem * 15 / 100)) 128 8192)
effective_cache=$(clamp $((mem * 50 / 100)) 256 65536)
maintenance_mem=$(clamp $((mem * 5 / 100)) 64 1024)
work_mem=16
((mem >= 8192)) && work_mem=32

mkdir -p "$conf_dir/conf.d"
cat > "$conf_dir/conf.d/90-odoo-jps.conf" << EOF
# Generated by /opt/odoo/jps/tune-postgres.sh for ${mem} MB RAM. Do not edit:
# put overrides in a file that sorts after this one, e.g. 99-local.conf

# No TCP at all: Odoo connects through the unix socket with peer authentication.
listen_addresses = ''
max_connections = 150

shared_buffers = ${shared_buffers}MB
effective_cache_size = ${effective_cache}MB
maintenance_work_mem = ${maintenance_mem}MB
work_mem = ${work_mem}MB

# SSD storage
random_page_cost = 1.1
effective_io_concurrency = 200

wal_compression = on
checkpoint_completion_target = 0.9
min_wal_size = 256MB
max_wal_size = 2GB

# Odoo runs many short queries: JIT compilation costs more than it saves.
jit = off

log_min_duration_statement = 2000
log_lock_waits = on
EOF

# Only local unix-socket connections, only for postgres and odoo, both as their OS user.
cat > "$conf_dir/pg_hba.conf" << 'EOF'
# Generated by /opt/odoo/jps/tune-postgres.sh
# TYPE  DATABASE  USER      METHOD
local   all       postgres  peer
local   all       odoo      peer
EOF

chown -R postgres:postgres "$conf_dir"

if ((restart)); then
  systemctl restart "postgresql@${PG_MAJOR}-main"
else
  systemctl reload "postgresql@${PG_MAJOR}-main" 2> /dev/null || true
fi
log "Postgres $PG_MAJOR tuned for ${mem} MB (shared_buffers ${shared_buffers}MB)"
