#!/usr/bin/env bash
# Generates the whole nginx configuration from the saved state, tests it and reloads.
# The config is always rewritten from scratch, so running this any number of times
# gives the same result (no in-place sed edits, no duplicated blocks).

. "$(dirname "$(readlink -f "$0")")/common.sh"
load_state

cert_name=odoo
le_dir=/etc/letsencrypt/live/$cert_name
self_dir=/etc/nginx/ssl

# Self-signed certificate for the default :443 server (direct IP access, unknown hosts).
if [ ! -s "$self_dir/selfsigned.crt" ]; then
  mkdir -p "$self_dir"
  openssl req -x509 -nodes -newkey rsa:2048 -days 3650 -subj "/CN=odoo-selfsigned" \
    -keyout "$self_dir/selfsigned.key" -out "$self_dir/selfsigned.crt" 2> /dev/null
  chmod 600 "$self_dir/selfsigned.key"
fi

mkdir -p "$ACME_ROOT" /var/cache/nginx/odoo
chown www-data:www-data /var/cache/nginx/odoo

# --- http-level settings --------------------------------------------------------
cat > /etc/nginx/conf.d/odoo-http.conf << 'EOF'
# Generated by /opt/odoo/jps/write-nginx.sh

upstream odoo {
    server 127.0.0.1:8069;
    keepalive 16;
}
upstream odoochat {
    server 127.0.0.1:8072;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# The Jelastic shared resolver terminates TLS for the environment domain and
# forwards plain HTTP with X-Forwarded-Proto; direct traffic uses our own scheme.
map $http_x_forwarded_proto $odoo_scheme {
    default $scheme;
    https   https;
}
map $request_uri $is_acme {
    ~^/\.well-known/acme-challenge/ 1;
    default 0;
}
map "$odoo_scheme:$is_acme" $redirect_to_https {
    "http:0" 1;
    default  0;
}

# Real client IP when the request comes through the Jelastic resolver (private ranges).
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from 100.64.0.0/10;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

# Brute-force brake on the login endpoints, per real client IP.
limit_req_zone $binary_remote_addr zone=odoo_login:10m rate=10r/m;
limit_req_status 429;

proxy_cache_path /var/cache/nginx/odoo levels=1:2 keys_zone=odoo_static:20m
                 max_size=1g inactive=7d use_temp_path=off;

server_tokens off;
client_max_body_size 256m;

# gzip itself is switched on in Ubuntu's nginx.conf
gzip_comp_level 5;
gzip_min_length 1024;
gzip_proxied any;
gzip_types text/css text/plain text/xml application/xml application/json
           application/javascript text/javascript image/svg+xml;
EOF

# --- snippets ---------------------------------------------------------------
mkdir -p /etc/nginx/snippets
cat > /etc/nginx/snippets/odoo-proxy-headers.conf << 'EOF'
# Generated by /opt/odoo/jps/write-nginx.sh
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $odoo_scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_redirect off;
proxy_connect_timeout 10s;
proxy_send_timeout 720s;
proxy_read_timeout 720s;
EOF

cat > /etc/nginx/snippets/odoo-locations.conf << 'EOF'
# Generated by /opt/odoo/jps/write-nginx.sh
# Odoo itself sends X-Frame-Options and X-Content-Type-Options.
add_header Referrer-Policy strict-origin-when-cross-origin always;

# The database manager is disabled (list_db = False); refuse it before Odoo sees it.
location ^~ /web/database/ {
    return 404;
}

location = /web/login {
    limit_req zone=odoo_login burst=10 nodelay;
    include snippets/odoo-proxy-headers.conf;
    proxy_pass http://odoo;
}
location = /web/session/authenticate {
    limit_req zone=odoo_login burst=10 nodelay;
    include snippets/odoo-proxy-headers.conf;
    proxy_pass http://odoo;
}
location = /web/reset_password {
    limit_req zone=odoo_login burst=5 nodelay;
    include snippets/odoo-proxy-headers.conf;
    proxy_pass http://odoo;
}

location /websocket {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $odoo_scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 3600s;
    proxy_pass http://odoochat;
}

# Static assets of every module: cached by nginx and by the browser.
location ~ ^/[^/]+/static/ {
    include snippets/odoo-proxy-headers.conf;
    proxy_cache odoo_static;
    proxy_cache_valid 200 60m;
    proxy_cache_use_stale error timeout updating;
    add_header X-Cache-Status $upstream_cache_status;
    expires 7d;
    proxy_pass http://odoo;
}

location / {
    include snippets/odoo-proxy-headers.conf;
    proxy_pass http://odoo;
}
EOF

# --- servers ----------------------------------------------------------------
# nginx >= 1.25.1 enables HTTP/2 with "http2 on"; older versions (Ubuntu 24.04 ships
# 1.24) need it on the listen line.
nginx_version=$(nginx -v 2>&1 | sed -n 's|.*nginx/\([0-9.]*\).*|\1|p')
if dpkg --compare-versions "$nginx_version" ge 1.25.1; then
  http2_listen="" http2_directive="http2 on;"
else
  http2_listen="http2" http2_directive=""
fi

{
  cat << 'EOF'
# Generated by /opt/odoo/jps/write-nginx.sh

# :80 serves the ACME challenge, the Jelastic resolver (already HTTPS on its side)
# and redirects every other plain-HTTP request to HTTPS.
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }
    if ($redirect_to_https) {
        return 301 https://$host$request_uri;
    }
    include snippets/odoo-locations.conf;
}

# :443 default: direct IP access and hosts without a Let's Encrypt certificate.
server {
    listen 443 ssl HTTP2_LISTEN default_server;
    listen [::]:443 ssl HTTP2_LISTEN default_server;
    HTTP2_DIRECTIVE
    server_name _;
    ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
    include snippets/odoo-tls.conf;
    include snippets/odoo-locations.conf;
}
EOF
  if [ -n "${DOMAINS:-}" ] && [ -s "$le_dir/fullchain.pem" ]; then
    cat << EOF

# Custom domains with the Let's Encrypt certificate (managed by ssl.sh).
server {
    listen 443 ssl ${http2_listen};
    listen [::]:443 ssl ${http2_listen};
    ${http2_directive}
    server_name ${DOMAINS};
    ssl_certificate     ${le_dir}/fullchain.pem;
    ssl_certificate_key ${le_dir}/privkey.pem;
    include snippets/odoo-tls.conf;
    add_header Strict-Transport-Security "max-age=15768000" always;
    include snippets/odoo-locations.conf;
}
EOF
  fi
} | sed -e "s/HTTP2_LISTEN/${http2_listen}/" -e "s/HTTP2_DIRECTIVE/${http2_directive}/" \
  > /etc/nginx/sites-available/odoo

# Mozilla "intermediate" TLS profile.
cat > /etc/nginx/snippets/odoo-tls.conf << 'EOF'
# Generated by /opt/odoo/jps/write-nginx.sh
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
ssl_prefer_server_ciphers off;
ssl_session_cache shared:odoo_tls:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;
EOF

# Containers without IPv6 would make nginx fail on the [::] listeners.
if [ ! -s /proc/net/if_inet6 ]; then
  sed -i '/listen \[::\]/d' /etc/nginx/sites-available/odoo
fi

ln -sfn /etc/nginx/sites-available/odoo /etc/nginx/sites-enabled/odoo
rm -f /etc/nginx/sites-enabled/default

if ! nginx -t 2> /tmp/nginx-test.log; then
  cat /tmp/nginx-test.log >&2
  die "nginx configuration test failed, not reloading"
fi
if systemctl is-active --quiet nginx; then
  systemctl reload nginx
else
  systemctl enable --now nginx
fi
log "nginx configuration written and reloaded"
