#!/usr/bin/env bash
# Regenerates /etc/odoo/odoo.conf from the saved state and the node's current size.
# Runs as ExecStartPre of odoo.service, so every restart picks up new cloudlet limits
# and any addons repository added under /opt/odoo/addons.
# Local overrides: put an [options] section in /etc/odoo/odoo.local.conf.

. "$(dirname "$(readlink -f "$0")")/common.sh"
load_state
[ -n "${ODOO_VERSION:-}" ] || die "no ODOO_VERSION in $STATE_FILE"

mem=$(mem_mb)
cpus=$(cpu_count)

# Sizing follows the Odoo deployment guide: one worker needs ~325 MB on average
# (80% light requests at ~150 MB, 20% heavy ones at ~1 GB). Odoo gets ~55% of the
# node's RAM; Postgres, nginx and the OS keep the rest (see tune-postgres.sh).
odoo_budget=$((mem * 55 / 100 - 200))
workers=$(clamp $((odoo_budget / 325)) 2 $((cpus * 2 + 1)))
workers=$(clamp "$workers" 2 32)
cron=1
((workers >= 8)) && cron=2

# Addons path: core addons, then /opt/odoo/addons itself if it holds modules, then
# every first-level directory that holds modules (e.g. a git checkout of an OCA repo).
is_addons_dir() { compgen -G "$1/*/__manifest__.py" > /dev/null; }
addons_path=$ODOO_CORE_ADDONS
if [ -d "$ADDONS_DIR" ]; then
  is_addons_dir "$ADDONS_DIR" && addons_path+=",$ADDONS_DIR"
  for d in "$ADDONS_DIR"/*/; do
    d=${d%/}
    [ -d "$d" ] && is_addons_dir "$d" && addons_path+=",$d"
  done
fi

# Odoo 19 turned demo data off by default and removed without_demo.
demo_line="without_demo = all"
(($(odoo_major) >= 19)) && demo_line=""

tmp=$(mktemp)
cat > "$tmp" << EOF
[options]
admin_passwd = ${ADMIN_PASSWD_HASH:-}
db_user = odoo
db_name = ${DB_NAME}
dbfilter = ^${DB_NAME}\$
list_db = False
db_maxconn = 32
proxy_mode = True
http_interface = 127.0.0.1
http_port = 8069
gevent_port = 8072
data_dir = ${ODOO_DATA}
addons_path = ${addons_path}
workers = ${workers}
max_cron_threads = ${cron}
limit_memory_soft = 629145600
limit_memory_hard = 1677721600
limit_time_cpu = 600
limit_time_real = 1200
limit_request = 65536
unaccent = True
${demo_line}
EOF

# Merge [options] from odoo.local.conf over the generated values.
python3 - "$tmp" "$ODOO_LOCAL_CONF" "$ODOO_CONF" << 'PY'
import configparser, os, sys
generated, local, target = sys.argv[1:4]
cfg = configparser.ConfigParser(interpolation=None)
cfg.optionxform = str
cfg.read(generated)
if os.path.exists(local):
    over = configparser.ConfigParser(interpolation=None)
    over.optionxform = str
    over.read(local)
    for section in over.sections():
        if not cfg.has_section(section):
            cfg.add_section(section)
        for k, v in over.items(section, raw=True):
            cfg.set(section, k, v)
with open(target + ".tmp", "w") as f:
    f.write("; Generated by /opt/odoo/jps/write-odoo-conf.sh on every Odoo start.\n")
    f.write("; Do not edit: put overrides in /etc/odoo/odoo.local.conf\n")
    cfg.write(f)
os.replace(target + ".tmp", target)
PY
rm -f "$tmp"
chown odoo:odoo "$ODOO_CONF"
chmod 640 "$ODOO_CONF"
